#!/bin/bash

#ffmpeg -i $1.avi -vf scale="trunc(iw/2)*2:trunc(ih/2)*2" -c:v libx264 -profile:v high -pix_fmt yuv420p -g 25 -r 25 $1.mp4
ffmpeg -i $1.avi  -c:v libx264 -profile:v high -pix_fmt yuv420p -g 25 -r 25 $1.mp4
ffmpeg -i $1.mp4 -vframes 1 -f image2 $1.png
convert $1.png -quality 95 $1.png
